#ifndef NETWORKCONFIG_H
#define NETWORKCONFIG_H

#define SERVER_ADDRESS "127.0.0.1"
#define SERVER_PORT 5555
#define BUFSIZE 512
#define MAX_PLAYERS 5
#define PACKET_BUFFER_SIZE 64
#define MAX_PROCESS_TIME 30

#endif